/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as TokenFurnaceContractJson } from "../TokenFurnace.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts";

// Custom types for the contract
export namespace TokenFurnaceTypes {
  export type Fields = {
    nftTemplateId: HexString;
    collectionUri: HexString;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type BurnedEvent = ContractEvent<{
    caller: Address;
    tokenBurned: HexString;
    amount: bigint;
    nft: boolean;
    timestamp: bigint;
  }>;

  export interface CallMethodTable {
    getCollectionUri: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    totalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    nftByIndex: {
      params: CallContractParams<{ index: bigint }>;
      result: CallContractResult<HexString>;
    };
    validateNFT: {
      params: CallContractParams<{ nftId: HexString; nftIndex: bigint }>;
      result: CallContractResult<null>;
    };
    burn: {
      params: CallContractParams<{
        tokenIdToBurn: HexString;
        amountToBurn: bigint;
        withNft: boolean;
      }>;
      result: CallContractResult<null>;
    };
    mint: {
      params: CallContractParams<{
        tokenIdBurned: HexString;
        amountBurned: bigint;
        burnerCaller: Address;
      }>;
      result: CallContractResult<HexString>;
    };
    convert: {
      params: CallContractParams<{ array: HexString }>;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getCollectionUri: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    totalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    nftByIndex: {
      params: SignExecuteContractMethodParams<{ index: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    validateNFT: {
      params: SignExecuteContractMethodParams<{
        nftId: HexString;
        nftIndex: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    burn: {
      params: SignExecuteContractMethodParams<{
        tokenIdToBurn: HexString;
        amountToBurn: bigint;
        withNft: boolean;
      }>;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: SignExecuteContractMethodParams<{
        tokenIdBurned: HexString;
        amountBurned: bigint;
        burnerCaller: Address;
      }>;
      result: SignExecuteScriptTxResult;
    };
    convert: {
      params: SignExecuteContractMethodParams<{ array: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  TokenFurnaceInstance,
  TokenFurnaceTypes.Fields
> {
  encodeFields(fields: TokenFurnaceTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Burned: 0 };
  consts = {
    ErrorCodes: {
      IncorrectTokenIndex: BigInt("0"),
      NFTNotFound: BigInt("1"),
      NFTNotPartOfCollection: BigInt("2"),
      TokenIdNotAccepted: BigInt("4"),
      CannotBurnZero: BigInt("5"),
    },
  };

  at(address: string): TokenFurnaceInstance {
    return new TokenFurnaceInstance(address);
  }

  tests = {
    getCollectionUri: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenFurnaceTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getCollectionUri",
        params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<TokenFurnaceTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "totalSupply", params, getContractByCodeHash);
    },
    nftByIndex: async (
      params: TestContractParamsWithoutMaps<
        TokenFurnaceTypes.Fields,
        { index: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "nftByIndex", params, getContractByCodeHash);
    },
    validateNFT: async (
      params: TestContractParamsWithoutMaps<
        TokenFurnaceTypes.Fields,
        { nftId: HexString; nftIndex: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "validateNFT", params, getContractByCodeHash);
    },
    burn: async (
      params: TestContractParamsWithoutMaps<
        TokenFurnaceTypes.Fields,
        { tokenIdToBurn: HexString; amountToBurn: bigint; withNft: boolean }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burn", params, getContractByCodeHash);
    },
    mint: async (
      params: TestContractParamsWithoutMaps<
        TokenFurnaceTypes.Fields,
        {
          tokenIdBurned: HexString;
          amountBurned: bigint;
          burnerCaller: Address;
        }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
    convert: async (
      params: TestContractParamsWithoutMaps<
        TokenFurnaceTypes.Fields,
        { array: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "convert", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: TokenFurnaceTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const TokenFurnace = new Factory(
  Contract.fromJson(
    TokenFurnaceContractJson,
    "",
    "d0e8cba96b5dfdb2fd41df2553d98529bacd65e3ec91d424aea8e07292c2b3e3",
    []
  )
);
registerContract(TokenFurnace);

// Use this class to interact with the blockchain
export class TokenFurnaceInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TokenFurnaceTypes.State> {
    return fetchContractState(TokenFurnace, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeBurnedEvent(
    options: EventSubscribeOptions<TokenFurnaceTypes.BurnedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TokenFurnace.contract,
      this,
      options,
      "Burned",
      fromCount
    );
  }

  view = {
    getCollectionUri: async (
      params?: TokenFurnaceTypes.CallMethodParams<"getCollectionUri">
    ): Promise<TokenFurnaceTypes.CallMethodResult<"getCollectionUri">> => {
      return callMethod(
        TokenFurnace,
        this,
        "getCollectionUri",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    totalSupply: async (
      params?: TokenFurnaceTypes.CallMethodParams<"totalSupply">
    ): Promise<TokenFurnaceTypes.CallMethodResult<"totalSupply">> => {
      return callMethod(
        TokenFurnace,
        this,
        "totalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    nftByIndex: async (
      params: TokenFurnaceTypes.CallMethodParams<"nftByIndex">
    ): Promise<TokenFurnaceTypes.CallMethodResult<"nftByIndex">> => {
      return callMethod(
        TokenFurnace,
        this,
        "nftByIndex",
        params,
        getContractByCodeHash
      );
    },
    validateNFT: async (
      params: TokenFurnaceTypes.CallMethodParams<"validateNFT">
    ): Promise<TokenFurnaceTypes.CallMethodResult<"validateNFT">> => {
      return callMethod(
        TokenFurnace,
        this,
        "validateNFT",
        params,
        getContractByCodeHash
      );
    },
    burn: async (
      params: TokenFurnaceTypes.CallMethodParams<"burn">
    ): Promise<TokenFurnaceTypes.CallMethodResult<"burn">> => {
      return callMethod(
        TokenFurnace,
        this,
        "burn",
        params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: TokenFurnaceTypes.CallMethodParams<"mint">
    ): Promise<TokenFurnaceTypes.CallMethodResult<"mint">> => {
      return callMethod(
        TokenFurnace,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
    convert: async (
      params: TokenFurnaceTypes.CallMethodParams<"convert">
    ): Promise<TokenFurnaceTypes.CallMethodResult<"convert">> => {
      return callMethod(
        TokenFurnace,
        this,
        "convert",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getCollectionUri: async (
      params: TokenFurnaceTypes.SignExecuteMethodParams<"getCollectionUri">
    ): Promise<
      TokenFurnaceTypes.SignExecuteMethodResult<"getCollectionUri">
    > => {
      return signExecuteMethod(TokenFurnace, this, "getCollectionUri", params);
    },
    totalSupply: async (
      params: TokenFurnaceTypes.SignExecuteMethodParams<"totalSupply">
    ): Promise<TokenFurnaceTypes.SignExecuteMethodResult<"totalSupply">> => {
      return signExecuteMethod(TokenFurnace, this, "totalSupply", params);
    },
    nftByIndex: async (
      params: TokenFurnaceTypes.SignExecuteMethodParams<"nftByIndex">
    ): Promise<TokenFurnaceTypes.SignExecuteMethodResult<"nftByIndex">> => {
      return signExecuteMethod(TokenFurnace, this, "nftByIndex", params);
    },
    validateNFT: async (
      params: TokenFurnaceTypes.SignExecuteMethodParams<"validateNFT">
    ): Promise<TokenFurnaceTypes.SignExecuteMethodResult<"validateNFT">> => {
      return signExecuteMethod(TokenFurnace, this, "validateNFT", params);
    },
    burn: async (
      params: TokenFurnaceTypes.SignExecuteMethodParams<"burn">
    ): Promise<TokenFurnaceTypes.SignExecuteMethodResult<"burn">> => {
      return signExecuteMethod(TokenFurnace, this, "burn", params);
    },
    mint: async (
      params: TokenFurnaceTypes.SignExecuteMethodParams<"mint">
    ): Promise<TokenFurnaceTypes.SignExecuteMethodResult<"mint">> => {
      return signExecuteMethod(TokenFurnace, this, "mint", params);
    },
    convert: async (
      params: TokenFurnaceTypes.SignExecuteMethodParams<"convert">
    ): Promise<TokenFurnaceTypes.SignExecuteMethodResult<"convert">> => {
      return signExecuteMethod(TokenFurnace, this, "convert", params);
    },
  };

  async multicall<Calls extends TokenFurnaceTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TokenFurnaceTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends TokenFurnaceTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<TokenFurnaceTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | TokenFurnaceTypes.MultiCallParams
      | TokenFurnaceTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      TokenFurnace,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
